/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fahri.perpus;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Unknown
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public mainMenu() {
        initComponents();
        load_table_mahasiswa();
        load_table_buku();
        load_table_pegawai();
        load_table_pinjam();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width, screen.height);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JPanel();
        btn_pinjam = new javax.swing.JLabel();
        btn_buku = new javax.swing.JLabel();
        btn_mahasiswa = new javax.swing.JLabel();
        btn_pegawai = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_credits = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        namauser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pinjam = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pinjam = new javax.swing.JTable();
        buku = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_buku = new javax.swing.JTable();
        pegawai = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_pegawai = new javax.swing.JTable();
        mahasiswa = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_mahasiswa = new javax.swing.JTable();
        credits = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        heading.setBackground(new java.awt.Color(74, 209, 161));

        btn_pinjam.setBackground(new java.awt.Color(0, 187, 150));
        btn_pinjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        btn_pinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jadwal.png"))); // NOI18N
        btn_pinjam.setText("Peminjaman");
        btn_pinjam.setOpaque(true);
        btn_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pinjamMouseClicked(evt);
            }
        });

        btn_buku.setBackground(new java.awt.Color(74, 209, 161));
        btn_buku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_buku.setForeground(new java.awt.Color(255, 255, 255));
        btn_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buku.png"))); // NOI18N
        btn_buku.setText("Buku");
        btn_buku.setOpaque(true);
        btn_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bukuMouseClicked(evt);
            }
        });

        btn_mahasiswa.setBackground(new java.awt.Color(74, 209, 161));
        btn_mahasiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_mahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mahasiswa.png"))); // NOI18N
        btn_mahasiswa.setText("Mahasiswa");
        btn_mahasiswa.setOpaque(true);
        btn_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mahasiswaMouseClicked(evt);
            }
        });

        btn_pegawai.setBackground(new java.awt.Color(74, 209, 161));
        btn_pegawai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_pegawai.setForeground(new java.awt.Color(255, 255, 255));
        btn_pegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pegawai.png"))); // NOI18N
        btn_pegawai.setText("Pegawai");
        btn_pegawai.setOpaque(true);
        btn_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pegawaiMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("e-PERPUSTAKAAN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("_______________");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("buku adalah jendela dunia");

        btn_credits.setBackground(new java.awt.Color(74, 209, 161));
        btn_credits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_credits.setForeground(new java.awt.Color(255, 255, 255));
        btn_credits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_credits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/credits.png"))); // NOI18N
        btn_credits.setText("Credits");
        btn_credits.setOpaque(true);
        btn_credits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_creditsMouseClicked(evt);
            }
        });

        search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));

        btn_search.setBackground(new java.awt.Color(87, 101, 116));
        btn_search.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_search.setForeground(new java.awt.Color(74, 209, 161));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btn_search.setBorderPainted(false);
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_search))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setBackground(new java.awt.Color(87, 101, 116));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namauser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namauser.setForeground(new java.awt.Color(255, 255, 255));
        namauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namauser.setText("Nama Pegawai");
        namauser.setPreferredSize(new java.awt.Dimension(79, 30));

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headingLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btn_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_credits, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headingLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(headingLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headingLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                        .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                        .addComponent(namauser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namauser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headingLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(headingLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_credits, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(87, 101, 116));

        btn_delete.setBackground(new java.awt.Color(74, 209, 161));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btn_delete.setText("Hapus ");
        btn_delete.setBorderPainted(false);
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_delete.setPreferredSize(new java.awt.Dimension(97, 35));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
        });
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(74, 209, 161));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btn_add.setText("Tambah");
        btn_add.setBorderPainted(false);
        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add.setPreferredSize(new java.awt.Dimension(97, 35));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(74, 209, 161));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.setBorderPainted(false);
        btn_refresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_refresh.setPreferredSize(new java.awt.Dimension(97, 35));
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_refreshMouseExited(evt);
            }
        });
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(74, 209, 161));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setBorderPainted(false);
        btn_edit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_edit.setPreferredSize(new java.awt.Dimension(97, 35));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 187, 150));

        jPanel1.setLayout(new java.awt.CardLayout());

        pinjam.setBackground(new java.awt.Color(255, 255, 255));
        pinjam.setLayout(new javax.swing.BoxLayout(pinjam, javax.swing.BoxLayout.LINE_AXIS));

        tb_pinjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_pinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pinjam.setGridColor(new java.awt.Color(240, 240, 240));
        tb_pinjam.setSelectionBackground(new java.awt.Color(29, 209, 161));
        jScrollPane1.setViewportView(tb_pinjam);

        pinjam.add(jScrollPane1);

        jPanel1.add(pinjam, "card2");

        buku.setLayout(new javax.swing.BoxLayout(buku, javax.swing.BoxLayout.LINE_AXIS));

        tb_buku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {"", null, null, null},
                {"", null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_buku.setGridColor(new java.awt.Color(240, 240, 240));
        tb_buku.setSelectionBackground(new java.awt.Color(29, 209, 161));
        jScrollPane2.setViewportView(tb_buku);

        buku.add(jScrollPane2);

        jPanel1.add(buku, "card3");

        pegawai.setBackground(new java.awt.Color(255, 255, 255));
        pegawai.setLayout(new javax.swing.BoxLayout(pegawai, javax.swing.BoxLayout.LINE_AXIS));

        tb_pegawai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pegawai.setGridColor(new java.awt.Color(240, 240, 240));
        tb_pegawai.setSelectionBackground(new java.awt.Color(29, 209, 161));
        jScrollPane3.setViewportView(tb_pegawai);

        pegawai.add(jScrollPane3);

        jPanel1.add(pegawai, "card2");

        mahasiswa.setBackground(new java.awt.Color(255, 255, 255));
        mahasiswa.setLayout(new javax.swing.BoxLayout(mahasiswa, javax.swing.BoxLayout.LINE_AXIS));

        tb_mahasiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_mahasiswa.setGridColor(new java.awt.Color(240, 240, 240));
        tb_mahasiswa.setSelectionBackground(new java.awt.Color(29, 209, 161));
        jScrollPane4.setViewportView(tb_mahasiswa);

        mahasiswa.add(jScrollPane4);

        jPanel1.add(mahasiswa, "card2");

        credits.setBackground(new java.awt.Color(87, 101, 116));
        credits.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Coder");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Icon Pack");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Material Design");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Muhammad Fahri Ramadhan");

        javax.swing.GroupLayout creditsLayout = new javax.swing.GroupLayout(credits);
        credits.setLayout(creditsLayout);
        creditsLayout.setHorizontalGroup(
            creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(creditsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(765, Short.MAX_VALUE))
        );
        creditsLayout.setVerticalGroup(
            creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel1.add(credits, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1323, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pinjamMouseClicked
        newcolor(btn_pinjam);
        resetcolor(btn_buku);
        resetcolor(btn_mahasiswa);
        resetcolor(btn_pegawai);
        resetcolor(btn_credits);
        pinjam.setVisible(true);
        buku.setVisible(false);
        mahasiswa.setVisible(false);
        pegawai.setVisible(false);
        credits.setVisible(false);
    }//GEN-LAST:event_btn_pinjamMouseClicked

    private void btn_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseClicked
        newcolor(btn_buku);
        resetcolor(btn_credits);
        resetcolor(btn_pinjam);
        resetcolor(btn_mahasiswa);
        resetcolor(btn_pegawai);
        buku.setVisible(true);
        pinjam.setVisible(false);
        mahasiswa.setVisible(false);
        pegawai.setVisible(false);
        credits.setVisible(false);
    }//GEN-LAST:event_btn_bukuMouseClicked

    private void btn_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pegawaiMouseClicked
        newcolor(btn_pegawai);
        resetcolor(btn_pinjam);
        resetcolor(btn_credits);
        resetcolor(btn_mahasiswa);
        resetcolor(btn_buku);
        pegawai.setVisible(true);
        pinjam.setVisible(false);
        mahasiswa.setVisible(false);
        buku.setVisible(false);
        credits.setVisible(false);
    }//GEN-LAST:event_btn_pegawaiMouseClicked

    private void btn_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswaMouseClicked
        newcolor(btn_mahasiswa);
        resetcolor(btn_credits);
        resetcolor(btn_pinjam);
        resetcolor(btn_buku);
        resetcolor(btn_pegawai);
        mahasiswa.setVisible(true);
        pinjam.setVisible(false);
        buku.setVisible(false);
        pegawai.setVisible(false);
        credits.setVisible(false);
    }//GEN-LAST:event_btn_mahasiswaMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if (mahasiswa.isVisible()) {
            String sql = "delete from mahasiswa Where npm=?";
            int tabelData = tb_mahasiswa.getSelectedRow();
            try {
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, tb_mahasiswa.getValueAt(tabelData, 0).toString());
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table_mahasiswa();
        } else if (pinjam.isVisible()) {
            String sql = "delete from pinjam Where id_pinjam=?";
            int tabelData = tb_pinjam.getSelectedRow();
            try {
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, tb_pinjam.getValueAt(tabelData, 0).toString());
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table_pinjam();
        } else if (buku.isVisible()) {
            String sql = "delete from buku Where kode_buku=?";
            int tabelData = tb_buku.getSelectedRow();
            try {
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, tb_buku.getValueAt(tabelData, 0).toString());
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table_buku();
        } else {
            String sql = "delete from pegawai Where nip=?";
            int tabelData = tb_pegawai.getSelectedRow();
            try {
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, tb_pegawai.getValueAt(tabelData, 0).toString());
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table_pegawai();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (mahasiswa.isVisible())
            new mahasiswaForm().setVisible(true);
        else if (pinjam.isVisible()) {
            viewnip();
        } else if (buku.isVisible())
            new bukuForm().setVisible(true);
        else
            new pegawaiForm().setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        if (mahasiswa.isVisible())
            load_table_mahasiswa();
        else if (pinjam.isVisible())
            load_table_pinjam();
        else if (buku.isVisible())
            load_table_buku();
        else
            load_table_pegawai();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (mahasiswa.isVisible()) {
            mahasiswaFormEdit mF = new mahasiswaFormEdit();
            mF.setVisible(true);
            int tabelData = tb_mahasiswa.getSelectedRow();
            mF.ambilnpm = (tb_mahasiswa.getValueAt(tabelData, 0).toString());
            mF.ambilnama = (tb_mahasiswa.getValueAt(tabelData, 1).toString());
            mF.ambiljurusan = (tb_mahasiswa.getValueAt(tabelData, 2).toString());
            mF.ambilkelas = (tb_mahasiswa.getValueAt(tabelData, 3).toString());
            mF.viewData();
        } else if (pinjam.isVisible()) {
            pinjamFormEdit piF = new pinjamFormEdit();
            piF.setVisible(true);
            int tabelData = tb_pinjam.getSelectedRow();
            piF.ambilkode = (tb_pinjam.getValueAt(tabelData, 1).toString());
            piF.ambilnip = (tb_pinjam.getValueAt(tabelData, 2).toString());
            piF.ambilnpm = (tb_pinjam.getValueAt(tabelData, 3).toString());
            piF.viewData();
            piF.view_buku();
            piF.view_mahasiswa();
            piF.view_pegawai();
        } else if (buku.isVisible()) {
            bukuFormEdit bF = new bukuFormEdit();
            bF.setVisible(true);
            int tabelData = tb_buku.getSelectedRow();
            bF.ambilkode = (tb_buku.getValueAt(tabelData, 0).toString());
            bF.ambiljudul = (tb_buku.getValueAt(tabelData, 1).toString());
            bF.ambilpenerbit = (tb_buku.getValueAt(tabelData, 2).toString());
            bF.ambilpengarang = (tb_buku.getValueAt(tabelData, 3).toString());
            bF.ambilthnterbit = (tb_buku.getValueAt(tabelData, 4).toString());
            bF.viewData();
        } else {
            pegawaiFormEdit pF = new pegawaiFormEdit();
            pF.setVisible(true);
            int tabelData = tb_pegawai.getSelectedRow();
            pF.ambilnip = (tb_pegawai.getValueAt(tabelData, 0).toString());
            pF.ambilnama = (tb_pegawai.getValueAt(tabelData, 1).toString());
            pF.viewData();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        hovercolor(btn_add);
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        defaultcolor(btn_add);
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        hovercolor(btn_edit);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        defaultcolor(btn_edit);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        hovercolor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        defaultcolor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseExited

    private void btn_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseEntered
        hovercolor(btn_refresh);
    }//GEN-LAST:event_btn_refreshMouseEntered

    private void btn_refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseExited
        defaultcolor(btn_refresh);
    }//GEN-LAST:event_btn_refreshMouseExited

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        if (mahasiswa.isVisible()) {
            search_mahasiswa();
        } else if (buku.isVisible()) {
            search_buku();
        } else if (pinjam.isVisible()) {
            search_pinjam();
        } else {
            search_pegawai();
        }
        search.setText(null);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        btn_search.setBackground(new java.awt.Color(86, 109, 148));
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        btn_search.setBackground(new java.awt.Color(87, 101, 116));
        btn_search.setForeground(new java.awt.Color(74, 209, 161));
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_creditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creditsMouseClicked
        newcolor(btn_credits);
        resetcolor(btn_mahasiswa);
        resetcolor(btn_pinjam);
        resetcolor(btn_buku);
        resetcolor(btn_pegawai);
        mahasiswa.setVisible(false);
        pinjam.setVisible(false);
        buku.setVisible(false);
        pegawai.setVisible(false);
        credits.setVisible(true);
    }//GEN-LAST:event_btn_creditsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void search_pinjam() {
        String cari = search.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Kode Buku");
        model.addColumn("NIP");
        model.addColumn("NPM");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Tanggal Kembali");

        try {
            String sql = "Select * from pinjam where "
                    + "id_pinjam like '%" + cari + "%' "
                    + "OR kode_buku like '%" + cari + "%' "
                    + "OR nip like '%" + cari + "%' "
                    + "OR npm like '%" + cari + "%' "
                    + "OR tgl_pinjam like '%" + cari + "%' "
                    + "OR tgl_kembali like '%" + cari + "%' "
                    + "order by id_pinjam asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                String id_pinjam = res.getString("id_pinjam");
                String kode_buku = res.getString("kode_buku");
                String nip = res.getString("nip");
                String npm = res.getString("npm");
                String tgl_pinjam = res.getString("tgl_pinjam");
                String tgl_kembali = res.getString("tgl_kembali");
                String[] dataField = {id_pinjam, kode_buku, nip, npm, tgl_pinjam, tgl_kembali};
                model.addRow(dataField);
            }
            tb_pinjam.setModel(model);
        } catch (Exception e) {
        }
    }

    private void search_pegawai() {
        String cari = search.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("Nama Pegawai");

        try {
            String sql = "Select * from pegawai where "
                    + "nip like '%" + cari + "%' "
                    + "OR nama_pegawai like '%" + cari + "%' "
                    + "order by nip asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                String nip = res.getString("nip");
                String nama_pegawai = res.getString("nama_pegawai");
                String[] dataField = {nip, nama_pegawai};
                model.addRow(dataField);
            }
            tb_pegawai.setModel(model);
        } catch (Exception e) {
        }
    }

    private void search_buku() {
        String cari = search.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Penerbit");
        model.addColumn("Pengarang");
        model.addColumn("Tahun Terbit");

        try {
            String sql = "Select * from buku where "
                    + "kode_buku like '%" + cari + "%' "
                    + "OR judul_buku like '%" + cari + "%' "
                    + "OR penerbit like '%" + cari + "%' "
                    + "OR pengarang like '%" + cari + "%' "
                    + "OR thn_terbit like '%" + cari + "%' "
                    + "order by kode_buku asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                String kode_buku = res.getString("kode_buku");
                String judul_buku = res.getString("judul_buku");
                String penerbit = res.getString("penerbit");
                String pengarang = res.getString("pengarang");
                String thn_terbit = res.getString("thn_terbit");
                String[] dataField = {kode_buku, judul_buku, penerbit, pengarang, thn_terbit};
                model.addRow(dataField);
            }
            tb_buku.setModel(model);
        } catch (Exception e) {
        }
    }

    private void search_mahasiswa() {
        String cari = search.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NPM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Jurusan");
        model.addColumn("Kelas");

        try {
            String sql = "Select * from mahasiswa where "
                    + "npm like '%" + cari + "%' "
                    + "OR nama_mahasiswa like '%" + cari + "%' "
                    + "OR jurusan like '%" + cari + "%' "
                    + "OR kelas like '%" + cari + "%' "
                    + "order by npm asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                String npm = res.getString("npm");
                String nama_mahasiswa = res.getString("nama_mahasiswa");
                String jurusan = res.getString("jurusan");
                String kelas = res.getString("kelas");
                String[] dataField = {npm, nama_mahasiswa, jurusan, kelas};
                model.addRow(dataField);
            }
            tb_mahasiswa.setModel(model);
        } catch (Exception e) {
        }
    }

//------------------------------------LOAD TABLE------------------------------
    private void load_table_pinjam() {
        tb_pinjam.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Kode Buku");
        model.addColumn("NIP");
        model.addColumn("NPM");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Tanggal Kembali");

        try {
            String sql = "select*from pinjam order by id_pinjam asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6)});
            }
            tb_pinjam.setModel(model);
        } catch (Exception e) {
        }
    }

    private void load_table_pegawai() {
        tb_pegawai.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("Nama Pegawai");

        try {
            String sql = "select*from pegawai order by nip asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(3)});
            }
            tb_pegawai.setModel(model);
        } catch (Exception e) {
        }
    }

    private void load_table_buku() {
        tb_buku.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Penerbit");
        model.addColumn("Pengarang");
        model.addColumn("Tahun Terbit");

        try {
            String sql = "select*from buku order by kode_buku asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                String date = res.getString(5);
                java.sql.Date dat = java.sql.Date.valueOf(date);
                Calendar cal = Calendar.getInstance();
                cal.setTime(dat);
                int year = cal.get(Calendar.YEAR);
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), year});
            }
            tb_buku.setModel(model);
        } catch (Exception e) {
        }
    }

    private void load_table_mahasiswa() {
        tb_mahasiswa.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NPM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Jurusan");
        model.addColumn("Kelas");

        try {
            String sql = "select*from mahasiswa order by npm asc";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            tb_mahasiswa.setModel(model);
        } catch (Exception e) {
        }
    }

//----------SET BUTTON COLOR----------------
    public void hovercolor(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(0, 187, 150));
    }

    public void defaultcolor(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(74, 209, 161));
    }

//----------SET LABEL COLOR-----------------
    public void newcolor(javax.swing.JLabel lbl) {
        lbl.setBackground(new java.awt.Color(0, 187, 150));
    }

    public void resetcolor(javax.swing.JLabel lbl) {
        lbl.setBackground(new java.awt.Color(74, 209, 161));
    }

    public String ambiluser;

    public String getambiluser() {
        return ambiluser;
    }

    //-----------View Login Account--------------
    public void viewData() {
        namauser.setText(ambiluser);
    }

    public void viewnip() {
        try {
            String sql = "select nip from pegawai where nama_pegawai='" + namauser.getText() + "';";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            if (res.next()) {
                pinjamForm pF = new pinjamForm();
                pF.ambilnip = res.getString("nip");
                pF.viewData();
                pF.setVisible(true);
            } else {
                System.out.println("Gagal menampilkan Nip");
            }
        } catch (Exception e) {
            System.out.println("Salah prosedur viewnip");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel btn_buku;
    private javax.swing.JLabel btn_credits;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JLabel btn_mahasiswa;
    private javax.swing.JLabel btn_pegawai;
    private javax.swing.JLabel btn_pinjam;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search;
    private javax.swing.JPanel buku;
    private javax.swing.JPanel credits;
    private javax.swing.JPanel heading;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mahasiswa;
    private javax.swing.JLabel namauser;
    private javax.swing.JPanel pegawai;
    private javax.swing.JPanel pinjam;
    private javax.swing.JTextField search;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tb_buku;
    private javax.swing.JTable tb_mahasiswa;
    private javax.swing.JTable tb_pegawai;
    private javax.swing.JTable tb_pinjam;
    // End of variables declaration//GEN-END:variables
}
